In [3]:
#Q1
import numpy as np
array1=[22,33,44]
array2=[21,33,45]
print(np.greater(array1,array2))
print(np.greater(array2,array1))
print(np.greater_equal(array1,array2))
print(np.greater_equal(array2,array1))

[ True False False]
[False False  True]
[ True  True False]
[False  True  True]


In [4]:
#Q2
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [23]:
#Q3
array3 = np.array([[3,23,12,43],[2,5,7,9],[23,32,98,42]])
print(np.sum(array3))


299


In [27]:
print(np.sum(array3,axis=0))
print(np.sum(array3,axis=1))

[ 28  60 117  94]
[ 81  23 195]


In [30]:
#Q4
print(np.add([2,3],[4,5]))
print(np.multiply([2,3],[4,5]))
print(np.subtract([8,9],[7,6]))
print(np.divide([10,8],[2,4]))

[6 8]
[ 8 15]
[1 3]
[5. 2.]


In [41]:
#Q5
array4 = np.array([0,30,45,60,90])
#conver degrees to radians the do computation in numpy it will take in radians
print(np.sin(np.deg2rad(array4)))

[0.         0.5        0.70710678 0.8660254  1.        ]


In [42]:
#Q6
import pandas as pd

dictionary1 = {"Student":["manisha", "sindu", "pranu", "amrita"],
             "Age":[25, 22, 18, 16],
             "college":["NIT", "IIIT", "MIT", "IIT"],
             "Country":["INDIA", "INDIA", "UK", "INDIA"]}

df = pd.DataFrame(dictionary1)
df

Student  Age college Country
0  manisha   25     NIT   INDIA
1    sindu   22    IIIT   INDIA
2    pranu   18     MIT      UK
3   amrita   16     IIT   INDIA

In [44]:
#Q7

df = pd.DataFrame({"Name":["Manisha", "Mike", "Bill", "Manny"],
                 "Age":[16,45,65,49],
                 "Score":[100,488,390,445]})

df[["Name","Score"]]

Name  Score
0  Manisha    100
1     Mike    488
2     Bill    390
3    Manny    445

In [46]:
#Q8
dataframe1 = pd.DataFrame({"Sports":["Soccer", "Boxing", "Football"],"Country":["India","germany","UK"]})

dataframe12 = pd.DataFrame({"Economy":["Higher", "Middle", "Low"],"History":["Ancient","Modern","Mideval"],"Country":["India","germany","UK"]})

result = dataframe1.merge(dataframe12,how="outer")
result

Sports  Country Economy  History
0    Soccer    India  Higher  Ancient
1    Boxing  germany  Middle   Modern
2  Football       UK     Low  Mideval

In [50]:
#Q9

df = pd.DataFrame({"Sports":["Soccer",np.nan, "Football"],"Country":["India","germany",np.nan]})


# We use the .isnull() to find null missing values it will print True/False
df.isnull()

Sports  Country
0   False    False
1    True    False
2   False     True

In [52]:
#Q10
array1 = [1,88,43,45]

res = pd.Series(array1)

print(type(res))
res

<class 'pandas.core.series.Series'>


0     1
1    88
2    43
3    45
dtype: int64